Models/BreedTypeModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PurrfectFeline.Models
{
    public class BreedTypeModel
    {
        public string Id { get; set; }
        public string Url { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<BreedTypeModel> LstOneCatBreed { get; set; }
    }
    
}

Models/CatBreedModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace PurrfectFeline.Models
  
{
    public class CatBreedModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
       public List<SelectListItem> LstBreed { get; set; }

      
    }

}

Models/CatInfoModel.cs
namespace PurrfectFeline.Models
{
    public class CatInfoModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Cfa_url { get; set; }
        public string Vetstreet_url { get; set; }
        public string Vcahospitals_url { get; set; }
        public string Temperament { get; set; }
        public string Origin { get; set; }
        public string Country_codes { get; set; }
        public string Description { get; set; }
        public string Life_span { get; set; }
        public int Indoor { get; set; }
        public int Lap { get; set; }
        public string Alt_names { get; set; }
        public int Adaptability  { get; set; }
        public int Affection_level { get; set; }
        public int Child_friendly { get;set; }
        public int Dog_friendly { get; set; }
        public int Energy_level { get; set; }
        public int Grooming { get; set; }
        public int Health_issues { get; set; }
        public int Intelligence { get; set; }
        public int Shedding_levelfe { get; set; }
        public int Social_needs { get; set; }
        public int Stranger_friendly { get; set; }
       public int Vocalisation { get; set; }
       public int Experimental { get; set; }
        public int Hairless { get; set; }
        public int Natural { get; set; }
        public int Rare { get; set; }
        public int Rex { get; set; }
        public int Suppressed_tail { get; set; }
        public string Wikipedia_url { get; set; }
        public int Hypoallergenic { get; set; }
        public string reference_image_id { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace PurrfectFeline.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ListCatsBreedsModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PurrfectFeline.Models
{
    public class ListCatsBreedsModel
    {

        public string Id { get; set; }
        public string Url { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public List<CatInfoModel> Breeds { get; set; }
        public List<SelectListItem> LstBreeds { get; set; }
        public List<BreedTypeModel> SelectedBreed { get; set; }
    }
}

Controllers/CatController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PurrfectFeline.Models;




namespace PurrfectFeline.Controllers
{
    public class CatController : Controller
    {
        public async Task<IActionResult> Breeds()
        {

            List<SelectListItem> LstBreed = new List<SelectListItem>();
            CatBreedModel catBreed = new CatBreedModel();

            ListCatsBreedsModel catList = new ListCatsBreedsModel();
            var client = new HttpClient();
            client.DefaultRequestHeaders.Add("x-api-key", "live_F9pFgfTNQsm0mJfBg0FpALoycqilewVeMw8LPpcsmqTZpsydTTRjvhINAQxvTyRE");

            var response = await client.GetAsync("https://api.thecatapi.com/v1/breeds");

            if (response.IsSuccessStatusCode)
            {
                var breedsJson = await response.Content.ReadAsStringAsync();
                var breeds = JsonConvert.DeserializeObject<List<CatBreedModel>>(breedsJson);

                if (breeds != null)
                {
                    foreach (var breed in breeds)
                    {
                        LstBreed.Add(new SelectListItem
                        {
                            Value = breed.Id,
                            Text = breed.Name,

                        });

                    }
                    if (LstBreed != null)
                    {
                        catBreed.LstBreed = LstBreed;
                        catList.LstBreeds = catBreed.LstBreed;
                    }

                }

                return View(catList);

            }

            return View("Error");
        }


        [HttpPost]
        public async Task<IActionResult> GetCatByBreed()
        {

            List<BreedTypeModel> LstOneCatBreed = new List<BreedTypeModel>();
            BreedTypeModel oneBreed = new BreedTypeModel();


            ListCatsBreedsModel selectedBreed = new ListCatsBreedsModel();



            var client = new HttpClient();
            string valorSeleccionado = Request.Form["breedId"];
            var response = await client.GetAsync("https://api.thecatapi.com/v1/images/search?limit=5&breed_ids=" + valorSeleccionado + "&api_key=live_F9pFgfTNQsm0mJfBg0FpALoycqilewVeMw8LPpcsmqTZpsydTTRjvhINAQxvTyRE");
            if (response.IsSuccessStatusCode)
            {
                var jsonGetOneBreed = await response.Content.ReadAsStringAsync();
                var getOneBreed = JsonConvert.DeserializeObject<List<BreedTypeModel>>(jsonGetOneBreed);


                if (getOneBreed != null)
                {

                    foreach (var catBreed in getOneBreed)
                    {
                        selectedBreed = new ListCatsBreedsModel();
                        selectedBreed.Id = catBreed.Id;
                        selectedBreed.Url = catBreed.Url;
                        selectedBreed.Width = catBreed.Width;
                        selectedBreed.Height = catBreed.Height;
                        selectedBreed.Breeds = catBreed.Breeds;


                        oneBreed = new BreedTypeModel();
                        oneBreed.Id = catBreed.Id;
                        oneBreed.Url = catBreed.Url;
                        oneBreed.Width = catBreed.Width;
                        oneBreed.Height = catBreed.Height;
                        oneBreed.Breeds = catBreed.Breeds;
                        LstOneCatBreed.Add(oneBreed);

                    }

                    if (getOneBreed != null)
                    {
                        oneBreed.LstOneCatBreed = LstOneCatBreed;

                        selectedBreed.SelectedBreed = LstOneCatBreed;

                    }
                    return View("Breeds", selectedBreed);
                }
            }
            return View("Error");
        }


    }
}

Controllers/CatListController.cs
using Microsoft.AspNetCore.Mvc;

namespace PurrfectFeline.Controllers
{
    public class CatListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CatsListController.cs
using Microsoft.AspNetCore.Mvc;

namespace PurrfectFeline.Controllers
{
    public class CatsListController : Controller
    {
        public IActionResult Index()
        {
            return View("CatsList");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PurrfectFeline.Models;
using System.Diagnostics;

namespace PurrfectFeline.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cat/Breeds.cshtml
@model ListCatsBreedsModel 

<h1>Breeds</h1>

<form asp-controller="Cat" asp-action="GetCatByBreed" method="post">
    <div class="form-group">
        <label for="breedId">Select a breed:</label>
        <select asp-items="@Model.LstBreeds" class="form-select" name="breedId">
           <option value="Name">select option</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
</form>

@if (Model.SelectedBreed != null) {
    @foreach (var cat in Model.SelectedBreed)
    {
        <img style="height:200px"src="@cat.Url"/>

        foreach (var breed in cat.Breeds)
        {
            <p>@breed.Description</p>
            <h1>@breed.Name</h1>
            <p>@breed.Lap</p>
            <p>@breed.Alt_names</p>
        }
    }

}

 <p><a asp-controller="Cat" asp-action="Breeds">Add new Favorite Cat</a></p>

Views/Cat/Index.cshtml
@model BreedTypeModel
@foreach (var cat in Model.LstOneCatBreed)
    {
        <img style="height:200px"src="@cat.Url"/>

        foreach (var breed in cat.Breeds)
        {
            <p>@breed.Description</p>
            <h1>@breed.Name</h1>
            <p>@breed.Lap</p>
            <p>@breed.Alt_names</p>
        }
    }

Views/CatList/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>List of cats</h1>

Views/CatsList/CatsList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>List of cats</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="HomePageImg">
        <h1 class="text-center">Welcome</h1>
         <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit sit amet sem 
          congue consequat. Suspendisse posuere.</p>
    </div>
       
    </div>
<div class="container">
  <div class="row">
    <div class="col-md-4 card">
      <img class="card-img-top" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.fchTwFEBDvwAbMb5Af32UQHaFj%26pid%3DApi&f=1&ipt=26b576dad12cd5889d0269ebda925ec5863e1886e0921689585807a46ff70edc&ipo=images" alt="Image"/>
      <h5 class="card-title">Card title</h5>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit sit amet sem 
          congue consequat. Suspendisse posuere sapien eget libero viverra, nec pretium purus feugiat. 
          Donec sed sapien vel elit rutrum tempus.</p>
    </div>

     <div class="col-md-4 card">
      <img class="card-img-top" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.mWm8chxvaTxoorDWAoVYfAHaFj%26pid%3DApi&f=1&ipt=37f2c607015e6754d98f9eeb53121c8f8814d1456a9f48552db1f837a184f5d3&ipo=images" alt="Image"/>
      <h5 class="card-title">Card title</h5>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit sit amet sem 
          congue consequat. Suspendisse posuere sapien eget libero viverra, nec pretium purus feugiat. 
          Donec sed sapien vel elit rutrum tempus.</p>
    </div>
     <div class="col-md-4 card">
      <img class="card-img-top" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.q9qj0S38Wg9kPayEDemz0gHaFj%26pid%3DApi&f=1&ipt=163aa7bc4ec3e8a4ad7003cdf74ec69d0e7fe967f75651cddb7a56a923848687&ipo=images" alt="Image"/>
      <h5 class="card-title">Card title</h5>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit sit amet sem 
          congue consequat. Suspendisse posuere sapien eget libero viverra, nec pretium purus feugiat. 
          Donec sed sapien vel elit rutrum tempus.</p>
    </div>

  </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PurrfectFeline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PurrfectFeline.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img style="height:55px"src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.tvKN41HeHKFUv2mtYiNhaQHaFj%26pid%3DApi&f=1&ipt=8e00d1e820434cfc16b80ff2b552aa9d33851aa048d04c17b85633f6b76de2cb&ipo=images"/>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PurrfectFeline</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cat" asp-action="Breeds">Breeds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CatList" asp-action="Index">Fav Cats</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PurrfectFeline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>